<head>
    <style>
        #link {
            text-align: center;
            padding-top: 10%;
        }

        
    </style>
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">

</head>

<div id="created-db">
    <div class="container">
        <div class="row">
            <h2></h2>


                <fieldset>
                    <legend>Database Created</legend>
                </fieldset>


        </div>
    </div>

    <div class="container">
        <div id="link">
            <center>
                <a  href="../book/success" class="btn btn-primary btn-lg">Go to Calendar</a>
            </center>
        </div>

    </div>
</div>


