<!-- Bootstrap core CSS -->
<head>
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<div id="create-db">
    <div class="container">
        <div class="row">
            <h2></h2>

            <form class="form-horizontal" name="db_form" method="post" action="createdatabase" onsubmit="return validateUserInputs()">
                <fieldset>

                    <!-- Form Name -->
                    <legend>Create Database Here</legend>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="textinput">Database Name</label>
                        <div class="col-md-4">
                            <input id="textinput" name="db_name" placeholder="Name your Database" class="form-control input-md" required="" type="text">
                            <span class="help-block"> </span>
                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="db_username">Username</label>
                        <div class="col-md-4">
                            <input id="db_username" name="db_username" placeholder="Enter Database Username" class="form-control input-md" required="" type="text">
                            <span class="help-block"> </span>
                        </div>
                    </div>



                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="passinput">Password</label>
                        <div class="col-md-4">
                            <input id="passinput" name="db_pass" placeholder="Password:Leave empty if no password set" class="form-control input-md"  type="password">
                            <span class="help-block"> </span>
                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="passinput">Confirm Password</label>
                        <div class="col-md-4">
                            <input id="passinput" name="db_passconfirm" placeholder="Password:Leave empty if no password set" class="form-control input-md" type="password">
                            <span class="help-block"> </span>
                        </div>
                    </div>



                    <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="create-button"> </label>
                        <div class="col-md-4">
                            <input id="create-button" type="submit" name="create_db" class="btn btn-primary" data-toggle="modal" data-target="#goto-calendar" value="Create Database">
                        </div>
                    </div>

                </fieldset>
            </form>

        </div>
    </div>
</div>


<script type="text/javascript">
    //form validation
    function validateUserInputs(){
        var db_username = document.forms['db_form']['db_username'].value;
        var db_pass     = document.forms['db_form']['db_pass'].value;
        var db_passconfirm     = document.forms['db_form']['db_passconfirm'].value;
        var db_name     = document.forms['db_form']['db_name'].value;

        if (db_pass !== db_passconfirm){
            alert("Your password do not match");
            return false;
        }

    }
    validateUserInputs();
</script>




