


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Room Booking Web App</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">



    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl() ?>/css/style.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<center>
    <a href="success" class="text-center">Go to Calendar</button></a>
</center>



<div class="container">



    <form class="form-signin" action="success" method="post">
        <h2 class="form-signin-heading text-center" >Book Room</h2>
        <!-- title-->
        <label for="inputTitle" class="sr-only">Email address</label>
        <input type="text" name="title" id="inputTitle" class="form-control" placeholder="Title" required autofocus>

        <!--Day-->

        <label for="inputDate" class="sr-only">Day</label>
        <input type="date" name="day" id="inputDate" class="form-control"  value="<?php echo $_POST['clickedday'];?>" required>

        <!--Start-->

        <label for="inputStartTime" class="sr-only">Start</label>
        <input type="time" name="start" id="inputStartTime" class="form-control"   required>

        <!--End-->

        <label for="inputEndTime" class="sr-only">End</label>
        <input type="time" name="end" id="inputEndTime" class="form-control"  required>

        <!--Submit-->

        <input class="btn btn-lg btn-primary btn-block" type="submit" name="book" value="Book">
    </form>

</div> <!-- /container -->



</body>
</html>
