<a href="index">
    <center><button class="">Book New Time</button></center>
</a>

<?php $events = (Zend_Json::encode($this->bookings));?>


<head>
    <title></title>
    <link rel='stylesheet' href="<?php echo $this->baseUrl()?>/css/fullcalendar.min.css "/>
    <script src="<?php echo $this->baseUrl()?>/js/jquery.min.js"></script>
    <script src="<?php echo $this->baseUrl()?>/js/moment.min.js"></script>
    <script src="<?php echo $this->baseUrl()?>/js/fullcalendar.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {

            // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
                // put your options and callbacks here
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                navLinks: true,
                selectable: true,
                selectHelper: true,
                eventLimit: true,
                events: <?php echo $events;?>
            })

        });
    </script>
    <style type="text/css">
        body {
            margin: 40px 10px;
            padding: 0;
            font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
            font-size: 14px;
        }

        #calendar {
            max-width: 900px;
            margin: 0 auto;
        }
    </style>
</head>
<body>

<div id='calendar'></div>


</body>





<?php

//echo count($this->bookings);

/*foreach($this->bookings as $booking){
    echo($booking[''] . ) ;
}
*/





?>